// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCRpZGI6ZzaLU3lCLN62nmL-mhOAw1rwk',
    appId: '1:760012649488:android:bb4c339c4017bfc484c695',
    messagingSenderId: '760012649488',
    projectId: 'zxcv-e1dd5',
    storageBucket: 'zxcv-e1dd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgkONam4pDvjD0tCHyty_omSq2ChwX8I',
    appId: '1:760012649488:ios:ff559c4852502ebe84c695',
    messagingSenderId: '760012649488',
    projectId: 'zxcv-e1dd5',
    storageBucket: 'zxcv-e1dd5.appspot.com',
    androidClientId: '760012649488-3erjv6b2rhgi863303fmse3jte6dppr7.apps.googleusercontent.com',
    iosClientId: '760012649488-0ctksqvqdtvg0qtr0fpmqu4016ncg7dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.backspace',
  );
}
